#
# Copyright (c) 2019 Nordic Semiconductor ASA
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#
# CONFIG_NCS_SAMPLES_DEFAULTS=y
CONFIG_MAIN_STACK_SIZE=4096
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=2048
# CONFIG_ESB=y
# # CONFIG_ESB_MAX_PAYLOAD_LENGTH=110
# CONFIG_ESB_MAX_PAYLOAD_LENGTH=77



#LOG subsystem related configs
CONFIG_LOG=y
CONFIG_LOG_MODE_DEFERRED=y
# CONFIG_USB_DRIVER_LOG_LEVEL_ERR=y
# CONFIG_USB_DEVICE_LOG_LEVEL_ERR=y
# CONFIG_USB_AUDIO_LOG_LEVEL_DBG=y


#net buf options
CONFIG_NET_BUF=y

# #USB audio related configs
# CONFIG_USB_DEVICE_AUDIO=y
# # CONFIG_USB_NRFX_EVT_QUEUE_SIZE=64
# CONFIG_USB_NRFX_WORK_QUEUE_STACK_SIZE=2048
# # CONFIG_USB_MCUX_THREAD_STACK_SIZE=2048
# # CONFIG_USB_DC_NUMAKER_MSG_HANDLER_THREAD_STACK_SIZE=2048
# CONFIG_RING_BUFFER=y
# CONFIG_USB_DEVICE_STACK=y
# CONFIG_USB_DEVICE_PRODUCT="Smart Remote dongle"


# Image manager
# CONFIG_STDOUT_CONSOLE=y
# CONFIG_FLASH=y
# CONFIG_MPU_ALLOW_FLASH_WRITE=y
# CONFIG_SOC_FLASH_NRF_EMULATE_ONE_BYTE_WRITE_ACCESS=y
# CONFIG_FCB=y
# CONFIG_FLASH_MAP=y
# CONFIG_SETTINGS=y
# CONFIG_SETTINGS_FCB=y


CONFIG_NCS_SAMPLES_DEFAULTS=y

## inverse esb config
CONFIG_MULTIACK_RADIO=y
CONFIG_MULTIACK_CENTRAL=y
CONFIG_MULTIACK_PERIPH=n
CONFIG_MULTIACK_DEBUG_GPIO=y

CONFIG_GPIO=y
CONFIG_NRF_GRTC_TIMER=y
CONFIG_NRFX_GPPI=y

CONFIG_FPU=y

CONFIG_PCM_MIX=y



